### PR TITLE
Add entry_point, remove deps unneeded with noarch

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- removes  some jinja variables
- updates some package metadata
- remove un-needed cross-build deps
- ensure the `shortuuid` CLI via `entry_points` 
- smoke test CLI
- use `poetry-core` instead of full-fat `poetry`
- add `pip check`
- ~~temporarily force creating the `py.typed` marker (upstream PR created)~~
- add self a maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/shortuuid ready for review :tada:

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/shortuuid added myself as a maintainer, and will request the core team to merge tomorrow if radio silence continues!

**Review by astamminger — APPROVED** [review]
Nice, thanks 👍

**Pull request merged**
